language: node_js
node_js:
  - 10
os:
  - linux
addons:
  apt:
    packages:
      - libsecret-1-dev
before_install:
  - yarn global add vsce
install:
  - yarn

script:
  - yarn run vscode:prepublish
