language: node
os:
  - linux
addons:
  apt:
    packages:
      - libsecret-1-dev
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install 8.9.1
  - nvm use 8.9.1
  - yarn global add vsce
install:
  - yarn

script:
  - yarn run clean
  - yarn run vscode:prepublish
  - if [ $TRAVIS_ENABLE_COVERAGE == "true" ]; then
        yarn run cover:enable;
    fi
  - yarn run test --silent
  - if [ $TRAVIS_ENABLE_COVERAGE == "true" ]; then
        yarn run cover:upload;
    fi