name: Github Release Notes

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install github-release-notes -g
      - run: gren release -d --override
        env:
          GREN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: gren changelog --override
        env:
          GREN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cat CHANGELOG.md
        
        